import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {useRouter} from "next/router"

import Header from "../components/commons/header";
import Footer from "../components/commons/footer";
import Card from "../components/card";
import ModalForm from "../components/modalForm";
import InitialText from "../components/initialText";
import { colors } from "../styles/theme";
import styles from "../styles/Home.module.css";

const initialForm = {
  aqueductName: "",
  idAqueduct: 0,
};

export default function Home() {
  const [Aqueduct, setAqueduct] = useState(null);
  const [AqueductModal, setAqueductModal] = useState(false);
  const [ArithmeticProjection, setArithmeticProjection] = useState(null);
  const router = useRouter();
  

  const handlePopulation = () =>{
    console.log(Aqueduct);
    router.push('/Projections/[id]' , `/Projections/${Aqueduct.idAqueduct}`)
  }
  const handleProp = () => {
    setAqueductModal(true);
  };

  return (
    <div className="">
      <Head>
        <title>Diseñador de Acueductos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header src={"/logo.png"}>Diseño de acueductos</Header>

        {!Aqueduct ? (
          <InitialText handleProp={handleProp} />
        ) : (
          <p>
            Diseñemos <b>{Aqueduct.aqueductName}</b>
          </p>
        )}

        <div className="row">
          <div className="col" onClick={Aqueduct && handlePopulation }>
            <Card
              src={"/poblacion.jpg"}
              title={"Proyecciones de poblacion"}
              dependency={Aqueduct}
            >
              Las proyecciones de población proporcionan una referencia del
              futuro tamaño y estructura de una población, basados en un
              conjunto de supuestos sobre el comportamiento de los componentes
              demográficos fecundidad, mortalidad y otros.
            </Card>
          </div>
          <div className="col">
            <Card src={"/DESARENADOR2.jpg"} title={"Desarenador"} dependency={ArithmeticProjection}>
              Los desarenadores son estructuras ubicadas a continuación de una
              captación de agua y que permiten remover partículas como arenas
              arcillas, gravas finas y material orgánico de cierto tamaño
              contenidas en el agua que ingresa de una fuente superficial
            </Card>
          </div>
        </div>
      </main>

      <Footer></Footer>

      {AqueductModal && (
        <ModalForm
          AqueductModal={AqueductModal}
          setAqueductModal={setAqueductModal}
          setAqueduct={setAqueduct}
        ></ModalForm>
      )}
      <style jsx>
        {`
          p {
            text-align: center;
            margin-top: 30px;
            font-size: 19px;
          }
          p b {
            font-size: 20px;
            color: ${colors.primary};
          }
        `}
      </style>
    </div>
  );
}
